"""
generator.py
============
Strictly-grounded legal answer generator 

Usage
-----
    from generator import generate_answer

    result = generate_answer("what to do if my phone is stolen")
    print(result.response)
    print(result.warnings)
"""

from __future__ import annotations

import os
import re
import textwrap
from dataclasses import dataclass, field

# ── Environment ───────────────────────────────────────────────────────────────
from dotenv import load_dotenv
load_dotenv()                        # reads .env from the project root

# ── LangChain core ────────────────────────────────────────────────────────────
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# ── Your retrieval pipeline ───────────────────────────────────────────────────
from retriever import retrieve, format_for_prompt

# ──────────────────────────────────────────────────────────────────────────────
# Configuration  (all overridable via .env)
# ──────────────────────────────────────────────────────────────────────────────

GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")
RETRIVAL_TOP_K=5

LEGAL_DISCLAIMER = (
    "\n\n---\n"
    "⚖️  **Disclaimer:** This response is generated by an AI legal information "
    "tool and is intended for general informational purposes only. It does NOT "
    "constitute legal advice, and no attorney-client relationship is formed by "
    "using this tool. Laws may have been amended; always verify with an "
    "up-to-date copy of the statute. For advice specific to your situation, "
    "please consult a qualified legal professional."
)

# ──────────────────────────────────────────────────────────────────────────────
# Data structure
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class GeneratorResult:
    query:          str
    response:       str
    snippets:       list[dict] = field(default_factory=list)
    verification_data: dict    = field(default_factory=dict)
    warnings:       list[str]  = field(default_factory=list)
    raw_llm_output: str        = ""
    


# ──────────────────────────────────────────────────────────────────────────────
# Layer 1 — Context Assembly
# ──────────────────────────────────────────────────────────────────────────────

def assemble_context(query: str, top_k: int = RETRIVAL_TOP_K) -> tuple[list[dict], str]:
    """
    Calls the 5-stage retrieval pipeline, returns:
      - snippets       : raw list[dict] for post-processing
      - context_block  : numbered citation string for the prompt
    """
    snippets = retrieve(query, top_k=top_k)
    if not snippets:
        return [], ""
    return snippets, format_for_prompt(snippets)


def _classify_chunk(chunk: dict) -> str:
    """'procedural' | 'statutory'  —  metadata-first, keyword fallback."""
    chunk_type = (chunk.get("chunk_type") or "").lower()
    if "procedural" in chunk_type or "instructional" in chunk_type:
        return "procedural"

    procedural_kws = {
        "step", "procedure", "file", "submit", "form", "application",
        "visit", "register", "complaint", "lodge", "approach", "contact",
        "handbook", "guide", "process", "how to",
    }
    if any(kw in (chunk.get("text") or "").lower() for kw in procedural_kws):
        return "procedural"
    return "statutory"


# ──────────────────────────────────────────────────────────────────────────────
# Layer 2 — Prompt Engineering  (LangChain ChatPromptTemplate)
# ──────────────────────────────────────────────────────────────────────────────

_SYSTEM_PERSONA = textwrap.dedent("""
    You are an expert Indian Legal Assistant with deep knowledge of Indian statutory
    law, including the Bharatiya Nyaya Sanhita (BNS), the Bharatiya Nagarik Suraksha
    Sanhita (BNSS), the Information Technology Act, and related legislation.

    STRICT GROUNDING RULES — follow these without exception:
    1. Answer ONLY from the numbered legal snippets in the [CONTEXT] block below.
    2. Append the snippet number (e.g., [1], [2]) after EVERY legal claim you make.
    3. NEVER invent, guess, or cite sections not present in [CONTEXT].
    4. If the answer is NOT in the snippets, respond with:
       "The provided legal excerpts do not contain sufficient information to answer
        this question. Please consult a legal professional."
    5. Do NOT add general legal knowledge beyond the snippets.

    RESPONSE STRUCTURE (use exactly these headings):
    ## Legal Position
    (High-level summary of the applicable law, cited.)

    ## Statutory Provisions
    (Specific sections, offences, punishments — from bare-act snippets, cited.)

    ## Procedural Steps / Action Plan
    (Step-by-step guidance — include ONLY when procedural snippets are present.)

    ## Key Points to Remember
    (Bullet list of critical takeaways, each cited.)
""").strip()

_HUMAN_TEMPLATE = textwrap.dedent("""
    [CONTEXT — use ONLY these snippets, cite each by its number]
    {context}

    [QUESTION]
    {question}
    {procedural_note}

    Provide a structured legal answer following your system instructions.
    Cite every claim using square-bracket snippet numbers, e.g. [1] or [2, 3].
""").strip()

# Reusable ChatPromptTemplate — built once at import time
_LEGAL_PROMPT = ChatPromptTemplate.from_messages([
    ("system", _SYSTEM_PERSONA),
    ("human",  _HUMAN_TEMPLATE),
])


# ──────────────────────────────────────────────────────────────────────────────
# LLM factory — reads .env, returns the correct LangChain chat model
# ──────────────────────────────────────────────────────────────────────────────

def _build_llm():
    """
    Instantiates the LangChain LLM defined by LLM_PROVIDER in .env.

    Install the relevant package for your chosen provider:
        pip install langchain-google-genai   # gemini
        pip install langchain-openai         # openai
        pip install langchain-anthropic      # anthropic
    """
    model_name = 'gemini-2.5-flash-lite' 

    from langchain_google_genai import ChatGoogleGenerativeAI
    return ChatGoogleGenerativeAI(
        model=model_name,
        temperature=0.0,
        max_output_tokens=1024,
        google_api_key=GEMINI_API_KEY,
    )


# ──────────────────────────────────────────────────────────────────────────────
# Layer 3 — Synthesis  (LangChain LCEL chain)
# ──────────────────────────────────────────────────────────────────────────────

def _build_chain():
    """LCEL chain: ChatPromptTemplate | LLM | StrOutputParser"""
    return _LEGAL_PROMPT | _build_llm() | StrOutputParser()


def synthesize(query: str, snippets: list[dict], context_block: str) -> str:
    """
    Invokes the LCEL chain with grounded context and returns the raw LLM answer.

    Chain input variables
    ---------------------
    context         — numbered citation block (from format_for_prompt)
    question        — user's legal query
    procedural_note — injected hint when procedural snippets are detected
    """
    has_procedural  = any(_classify_chunk(s) == "procedural" for s in snippets)
    procedural_note = (
        "\nNote: Some snippets contain procedural/instructional content — "
        "extract them into the 'Procedural Steps / Action Plan' section."
        if has_procedural else ""
    )

    chain = _build_chain()
    return chain.invoke({
        "context":         context_block,
        "question":        query,
        "procedural_note": procedural_note,
    })


# ──────────────────────────────────────────────────────────────────────────────
# Layer 4 — Post-Processing  (citation verification + disclaimer injection)
# ──────────────────────────────────────────────────────────────────────────────

_SECTION_PATTERN = re.compile(
    r"\b(?:Section|Sec\.?|s\.)\s*(\d+[A-Z]?(?:\(\w+\))*)"
    r"|§\s*(\d+[A-Z]?)",
    re.IGNORECASE,
)


def _section_nums_in_text(text: str) -> set[str]:
    found: set[str] = set()
    for m in _SECTION_PATTERN.finditer(text):
        raw = m.group(1) or m.group(2)
        if raw:
            found.add(re.split(r"[\(.]", raw)[0].strip())
    return found


def _section_nums_in_snippets(snippets: list[dict]) -> set[str]:
    available: set[str] = set()
    for s in snippets:
        sec = str(s.get("section_number", "")).strip()
        if sec:
            available.add(re.split(r"[\(.]", sec)[0].strip())
    return available


def verify_citations(llm_output: str, snippets: list[dict]) -> list[str]:
    """
    Diffs section numbers in the LLM answer against the retrieved snippets.
    Returns warning strings for any hallucinated section references.
    """
    hallucinated = _section_nums_in_text(llm_output) - _section_nums_in_snippets(snippets)
    return [
        f"⚠️  Section {sec} cited by the model is NOT in the retrieved snippets "
        f"— verify this reference independently."
        for sec in sorted(hallucinated, key=lambda x: int(re.sub(r"\D", "0", x)))
    ]


def inject_disclaimer(text: str) -> str:
    """Appends the mandatory legal disclaimer."""
    return text.rstrip() + LEGAL_DISCLAIMER





# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def generate_answer(
    query:  str,
    top_k:  int  = RETRIVAL_TOP_K,
    verify: bool = True,
) -> GeneratorResult:
    
    print(f"\n{'═' * 60}")
    print(f"[Generator] Query    : {query}")
    print("─" * 60)

    # ── Layer 1 ───────────────────────────────────────────────────────────
    snippets, context_block = assemble_context(query, top_k=top_k)

    if not snippets:
        return GeneratorResult(
            query=query,
            response=(
                "## No Relevant Legal Provisions Found\n\n"
                "The retrieval system could not find legal provisions relevant to "
                "your query. Please rephrase or consult a legal professional."
                + LEGAL_DISCLAIMER
            ),
            warnings=["Retrieval returned 0 results."],
        )

    print(f"[Generator] {len(snippets)} snippet(s) assembled.")

    # ── Layers 2 & 3 ─────────────────────────────────────────────────────
    print("[Generator] Running LangChain LCEL chain…")
    raw_output = synthesize(query, snippets, context_block)
    print("[Generator] Chain completed.")

    # ── Layer 4 ───────────────────────────────────────────────────────────
    from verifier import verify as run_verification
    
    verification_results = run_verification(raw_output, snippets)
    
    final_response = inject_disclaimer(raw_output)
    confidence_label = verification_results["confidence"]["label"]
    print(f"[Generator] {confidence_label}")
    
    if verification_results["risk_flag"]:
        risk = verification_results["risk_flag"]
        print(f"[Generator] {risk['label']}")
        for phrase in risk['matched_phrases']:
            print(f"            ↳ Triggered by: '{phrase}'")

    return GeneratorResult(
        query             = query,
        response          = final_response,
        snippets          = snippets,
        verification_data = verification_results,
        warnings       =[],
        raw_llm_output    = raw_output
        
    )


# ──────────────────────────────────────────────────────────────────────────────
# CLI demo
# ──────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    demo_queries = [
        "what to do if my phone is stolen",
        "being assaulted in a public place, what can I do?",
        "personal data leak from a website",
    ]

    for q in demo_queries:
        result = generate_answer(q)

        print("\n" + "═" * 70)
        print(f"QUERY  : {result.query}")
        print("─" * 70)
        print(result.response)

        if result.warnings:
            print("\n⚠️  CITATION WARNINGS:")
            for w in result.warnings:
                print(f"   {w}")

        print("═" * 70)